"""
Unified strategy state management abstractions.

Provides:
  - ``SearchContext`` — shared state accessible to all strategies
  - ``SearchStrategy`` — protocol that all strategies implement
  - ``StatefulStrategy`` — optional protocol for strategies with saveable state
  - ``StrategySnapshot`` — serialized state from one strategy
  - ``FactorCatalog`` — queryable registry of all factors across strategies
  - ``build_individual`` — compile a formula into an Individual
"""

from __future__ import annotations

from collections import defaultdict, deque
from dataclasses import asdict, dataclass, field
from typing import Any, Callable, Protocol, runtime_checkable

from loguru import logger


# ---------------------------------------------------------------------------
# Stateful strategy protocol
# ---------------------------------------------------------------------------


@dataclass
class StrategySnapshot:
    """Opaque serialized state from one strategy.

    ``data`` is raw bytes — the strategy decides the serialization format
    (PyTorch state_dict, JSON, etc.).  ``format`` is a tag so the
    checkpoint manager can sanity-check before loading.
    """

    strategy_name: str
    round_idx: int
    format: str  # "pt_state_dict" | "json"
    data: bytes
    metadata: dict[str, Any] = field(default_factory=dict)


@runtime_checkable
class StatefulStrategy(Protocol):
    """Optional interface for strategies that carry state across rounds.

    Strategies that implement this get automatic checkpoint/restore
    from the orchestrator.  Strategies that don't implement it are
    completely unaffected — the orchestrator detects support via
    ``isinstance(strategy, StatefulStrategy)``.
    """

    def save_state(self) -> StrategySnapshot:
        """Serialize internal state (model weights, tree, etc.) to bytes."""
        ...

    def load_state(self, snapshot: StrategySnapshot) -> None:
        """Restore internal state from a previous snapshot."""
        ...


# ---------------------------------------------------------------------------
# Factor catalog
# ---------------------------------------------------------------------------


@dataclass
class FactorCatalogEntry:
    """One factor generated by any strategy."""

    formula: str
    expr_hash: str
    strategy: str  # "neural_formula" | "mcts_refinement" | "llm_evolution" | ...
    round_idx: int
    rank_ic: float = 0.0
    sharpe: float = 0.0
    turnover: float = 0.0
    fitness: float = 0.0
    evaluated: bool = False
    lineage: dict[str, Any] = field(default_factory=dict)
    extra: dict[str, Any] = field(default_factory=dict)


class FactorCatalog:
    """Unified, queryable registry of all factors across strategies.

    Populated by the orchestrator after each evaluation batch.
    Persisted as part of checkpoint.
    """

    def __init__(self, max_entries: int = 5000) -> None:
        self._entries: list[FactorCatalogEntry] = []
        self._by_hash: dict[str, FactorCatalogEntry] = {}
        self._max_entries = max_entries

    def __len__(self) -> int:
        return len(self._entries)

    # --- mutation ---

    def record(self, entry: FactorCatalogEntry) -> None:
        """Add or update a factor entry."""
        existing = self._by_hash.get(entry.expr_hash)
        if existing is not None:
            # Update with evaluation results if newly evaluated
            if entry.evaluated and not existing.evaluated:
                existing.rank_ic = entry.rank_ic
                existing.sharpe = entry.sharpe
                existing.turnover = entry.turnover
                existing.fitness = entry.fitness
                existing.evaluated = True
            return
        self._entries.append(entry)
        self._by_hash[entry.expr_hash] = entry
        if len(self._entries) > self._max_entries:
            self._evict()

    # --- query ---

    def query(
        self,
        *,
        strategy: str | None = None,
        round_idx: int | None = None,
        min_ic: float | None = None,
        evaluated_only: bool = False,
        limit: int = 100,
    ) -> list[FactorCatalogEntry]:
        results = self._entries
        if strategy is not None:
            results = [e for e in results if e.strategy == strategy]
        if round_idx is not None:
            results = [e for e in results if e.round_idx == round_idx]
        if min_ic is not None:
            results = [e for e in results if abs(e.rank_ic) >= min_ic]
        if evaluated_only:
            results = [e for e in results if e.evaluated]
        return sorted(results, key=lambda e: e.fitness, reverse=True)[:limit]

    def get(self, expr_hash: str) -> FactorCatalogEntry | None:
        return self._by_hash.get(expr_hash)

    def stats_by_strategy(self) -> dict[str, dict[str, Any]]:
        """Per-strategy summary statistics."""
        groups: dict[str, list[FactorCatalogEntry]] = defaultdict(list)
        for e in self._entries:
            groups[e.strategy].append(e)
        result: dict[str, dict[str, Any]] = {}
        for strat, entries in groups.items():
            evaluated = [e for e in entries if e.evaluated]
            result[strat] = {
                "total_generated": len(entries),
                "total_evaluated": len(evaluated),
                "best_fitness": max((e.fitness for e in evaluated), default=0.0),
                "avg_ic": (
                    sum(abs(e.rank_ic) for e in evaluated) / len(evaluated)
                    if evaluated
                    else 0.0
                ),
            }
        return result

    # --- serialization ---

    def to_json_list(self) -> list[dict[str, Any]]:
        return [asdict(e) for e in self._entries]

    @classmethod
    def from_json_list(
        cls, data: list[dict[str, Any]], max_entries: int = 5000
    ) -> FactorCatalog:
        catalog = cls(max_entries=max_entries)
        for d in data:
            try:
                catalog.record(FactorCatalogEntry(**d))
            except TypeError:
                continue
        return catalog

    # --- internal ---

    def _evict(self) -> None:
        """Evict lowest-value entries to stay within capacity."""
        self._entries.sort(key=lambda e: (e.evaluated, e.fitness))
        while len(self._entries) > self._max_entries:
            removed = self._entries.pop(0)
            self._by_hash.pop(removed.expr_hash, None)


# ---------------------------------------------------------------------------
# Search strategy protocol
# ---------------------------------------------------------------------------


@runtime_checkable
class SearchStrategy(Protocol):
    """Interface that all search strategies must implement.

    To add a new strategy (e.g. from a paper), implement these 4 methods
    and register the strategy with SearchOrchestrator.
    """

    @property
    def name(self) -> str:
        """Strategy name for logging and tracing."""
        ...

    def should_activate(self, ctx: "SearchContext") -> bool:
        """Whether this strategy should run in the current round."""
        ...

    def generate_candidates(self, ctx: "SearchContext") -> list:
        """Generate candidate Individuals (compiled, not yet evaluated)."""
        ...

    def on_evaluation_complete(self, ctx: "SearchContext", evaluated: list) -> None:
        """Callback after evaluation — for internal learning."""
        ...


# ---------------------------------------------------------------------------
# Shared search context
# ---------------------------------------------------------------------------


@dataclass
class SearchContext:
    """Shared state accessible to all strategies via a single object.

    Strategies read/write population and archive through this context,
    enabling indirect collaboration without direct coupling.
    """

    # --- shared collections ---
    population: deque
    archive: dict[tuple[int, int], Any]  # cell -> Individual
    seen_hashes: set[str]
    all_evaluated: list
    details_by_hash: dict[str, dict[str, Any]]

    # --- infrastructure ---
    compiler: Any  # FormulaCompiler
    schema: Any  # TensorSchema
    registry: Any  # OperatorRegistry
    fitness_engine: Any  # FitnessEngine

    # --- evaluation callbacks ---
    evaluate_fn: Callable
    quick_evaluate_fn: Callable | None

    # --- optional enhanced modules ---
    strategy_memory: Any | None  # StrategyMemory
    knowledge_base: Any | None  # FinancialKnowledgeBase
    feature_kitchen: Any | None  # FeatureKitchen

    # --- VM (needed by strategies for fast screening) ---
    vm: Any | None = None  # StackVM

    # --- dataset (needed by some strategies like MCTS) ---
    dataset: Any | None = None  # AlphaDataset

    # --- search state ---
    round_idx: int = 0
    total_rounds: int = 0
    total_evaluations: int = 0
    total_rejected: int = 0
    batch_size: int = 8

    # --- factor catalog (unified factor tracking) ---
    factor_catalog: FactorCatalog | None = None


# ---------------------------------------------------------------------------
# Individual builder
# ---------------------------------------------------------------------------


def build_individual(
    compiler: Any,
    schema: Any,
    formula: str,
    lineage: Any,
) -> Any | None:
    """Compile a formula into an Individual, or return None on failure.

    Avoids circular imports by deferring the actual construction.
    """
    from .evolution import Individual
    from .pipeline import Lineage

    try:
        program = compiler.compile(formula, schema)
    except (ValueError, SyntaxError):
        return None
    if isinstance(lineage, dict):
        lineage = Lineage.from_dict(lineage)
    return Individual(
        formula=formula,
        program=program,
        expr_hash=program.expr_hash,
        lineage=lineage,
    )
