"""
Unified strategy state management abstractions.

Provides:
  - ``SearchContext`` — shared state accessible to all strategies
  - ``SearchStrategy`` — protocol that all strategies implement
  - ``StatefulStrategy`` — optional protocol for strategies with saveable state
  - ``StrategySnapshot`` — serialized state from one strategy
  - ``FactorCatalog`` — queryable registry of all factors across strategies
  - ``build_individual`` — compile a formula into an Individual
"""

from __future__ import annotations

from collections import defaultdict, deque
from dataclasses import asdict, dataclass, field
from typing import Any, Callable, Protocol, runtime_checkable

# ---------------------------------------------------------------------------
# Stateful strategy protocol
# ---------------------------------------------------------------------------


@dataclass
class StrategySnapshot:
    """Opaque serialized state from one strategy.

    ``data`` is raw bytes — the strategy decides the serialization format
    (PyTorch state_dict, JSON, etc.).  ``format`` is a tag so the
    checkpoint manager can sanity-check before loading.
    """

    strategy_name: str
    round_idx: int
    format: str  # "pt_state_dict" | "json"
    data: bytes
    metadata: dict[str, Any] = field(default_factory=dict)


@runtime_checkable
class StatefulStrategy(Protocol):
    """Optional interface for strategies that carry state across rounds.

    Strategies that implement this get automatic checkpoint/restore
    from the orchestrator.  Strategies that don't implement it are
    completely unaffected — the orchestrator detects support via
    ``isinstance(strategy, StatefulStrategy)``.
    """

    def save_state(self) -> StrategySnapshot:
        """Serialize internal state (model weights, tree, etc.) to bytes."""
        ...

    def load_state(self, snapshot: StrategySnapshot) -> None:
        """Restore internal state from a previous snapshot."""
        ...


# ---------------------------------------------------------------------------
# Factor catalog
# ---------------------------------------------------------------------------


def _compute_decay_rate(ic_history: list[float]) -> float:
    """Simple linear regression slope of IC values over observations."""
    n = len(ic_history)
    if n < 2:
        return 0.0
    x_mean = (n - 1) / 2.0
    y_mean = sum(ic_history) / n
    num = sum((i - x_mean) * (y - y_mean) for i, y in enumerate(ic_history))
    den = sum((i - x_mean) ** 2 for i in range(n))
    return num / den if den > 0 else 0.0


@dataclass
class FactorCatalogEntry:
    """One factor generated by any strategy."""

    formula: str
    expr_hash: str
    strategy: str  # "neural_formula" | "mcts_refinement" | "llm_evolution" | ...
    round_idx: int
    rank_ic: float = 0.0
    sharpe: float = 0.0
    turnover: float = 0.0
    fitness: float = 0.0
    evaluated: bool = False
    lineage: dict[str, Any] = field(default_factory=dict)
    parent_hashes: list[str] = field(default_factory=list)
    extra: dict[str, Any] = field(default_factory=dict)
    # Lifecycle tracking
    ic_history: list[float] = field(default_factory=list)
    created_at: str = ""
    decay_rate: float = 0.0  # slope of IC decline (negative = decaying)


class FactorCatalog:
    """Unified, queryable registry of all factors across strategies.

    Populated by the orchestrator after each evaluation batch.
    Persisted as part of checkpoint.
    """

    def __init__(self, max_entries: int = 5000) -> None:
        self._entries: list[FactorCatalogEntry] = []
        self._by_hash: dict[str, FactorCatalogEntry] = {}
        self._max_entries = max_entries

    def __len__(self) -> int:
        return len(self._entries)

    # --- mutation ---

    def record(self, entry: FactorCatalogEntry) -> None:
        """Add or update a factor entry."""
        existing = self._by_hash.get(entry.expr_hash)
        if existing is not None:
            # Update with evaluation results if newly evaluated
            if entry.evaluated and not existing.evaluated:
                existing.rank_ic = entry.rank_ic
                existing.sharpe = entry.sharpe
                existing.turnover = entry.turnover
                existing.fitness = entry.fitness
                existing.evaluated = True
            # Track IC history for lifecycle monitoring
            if entry.evaluated and entry.rank_ic != 0.0:
                existing.ic_history.append(entry.rank_ic)
                if len(existing.ic_history) >= 3:
                    existing.decay_rate = _compute_decay_rate(existing.ic_history)
            return
        if not entry.created_at:
            from datetime import datetime, timezone
            entry.created_at = datetime.now(timezone.utc).isoformat()
        if entry.evaluated and entry.rank_ic != 0.0:
            entry.ic_history.append(entry.rank_ic)
        self._entries.append(entry)
        self._by_hash[entry.expr_hash] = entry
        if len(self._entries) > self._max_entries:
            self._evict()

    def decaying_factors(self, threshold: float = -0.01) -> list[FactorCatalogEntry]:
        """Return factors whose IC is declining (decay_rate < threshold)."""
        return [
            e for e in self._entries
            if e.evaluated and len(e.ic_history) >= 3 and e.decay_rate < threshold
        ]

    def healthy_factors(self, min_ic: float = 0.02) -> list[FactorCatalogEntry]:
        """Return factors with stable or improving IC above min_ic."""
        return [
            e for e in self._entries
            if e.evaluated and abs(e.rank_ic) >= min_ic and e.decay_rate >= 0
        ]

    # --- query ---

    def query(
        self,
        *,
        strategy: str | None = None,
        round_idx: int | None = None,
        min_ic: float | None = None,
        evaluated_only: bool = False,
        limit: int = 100,
    ) -> list[FactorCatalogEntry]:
        results = self._entries
        if strategy is not None:
            results = [e for e in results if e.strategy == strategy]
        if round_idx is not None:
            results = [e for e in results if e.round_idx == round_idx]
        if min_ic is not None:
            results = [e for e in results if abs(e.rank_ic) >= min_ic]
        if evaluated_only:
            results = [e for e in results if e.evaluated]
        return sorted(results, key=lambda e: e.fitness, reverse=True)[:limit]

    def get(self, expr_hash: str) -> FactorCatalogEntry | None:
        return self._by_hash.get(expr_hash)

    def stats_by_strategy(self) -> dict[str, dict[str, Any]]:
        """Per-strategy summary statistics."""
        groups: dict[str, list[FactorCatalogEntry]] = defaultdict(list)
        for e in self._entries:
            groups[e.strategy].append(e)
        result: dict[str, dict[str, Any]] = {}
        for strat, entries in groups.items():
            evaluated = [e for e in entries if e.evaluated]
            result[strat] = {
                "total_generated": len(entries),
                "total_evaluated": len(evaluated),
                "best_fitness": max((e.fitness for e in evaluated), default=0.0),
                "avg_ic": (
                    sum(abs(e.rank_ic) for e in evaluated) / len(evaluated)
                    if evaluated
                    else 0.0
                ),
            }
        return result

    # --- retrieval (for strategies) ---

    def top_k(self, k: int = 20) -> list[FactorCatalogEntry]:
        """Top-K evaluated factors by fitness."""
        return sorted(
            (e for e in self._entries if e.evaluated),
            key=lambda e: e.fitness, reverse=True,
        )[:k]

    def diverse_top_k(
        self,
        k: int = 20,
        max_corr: float = 0.7,
        signal_fn: Any = None,
    ) -> list[FactorCatalogEntry]:
        """Top-K with pairwise correlation filtering.

        ``signal_fn(expr_hash) -> np.ndarray | None`` provides the alpha
        signal for correlation checks. If None, skips diversity filtering.
        """
        candidates = self.top_k(k=k * 3)
        if signal_fn is None or not candidates:
            return candidates[:k]

        import numpy as _np
        selected: list[FactorCatalogEntry] = []
        selected_signals: list[_np.ndarray] = []
        for entry in candidates:
            if len(selected) >= k:
                break
            sig = signal_fn(entry.expr_hash)
            if sig is None:
                continue
            flat = sig.flatten()
            flat = flat[~_np.isnan(flat)]
            if flat.size < 100:
                continue
            # Check correlation against already selected
            too_similar = False
            for prev in selected_signals:
                min_len = min(len(flat), len(prev))
                corr = _np.corrcoef(flat[:min_len], prev[:min_len])[0, 1]
                if abs(corr) > max_corr:
                    too_similar = True
                    break
            if not too_similar:
                selected.append(entry)
                selected_signals.append(flat)
        return selected

    def lineage_parents(self, expr_hash: str) -> list[FactorCatalogEntry]:
        """All ancestors of a factor (walk parent_hashes recursively)."""
        visited: set[str] = set()
        result: list[FactorCatalogEntry] = []
        queue = list(self._by_hash[expr_hash].parent_hashes) if expr_hash in self._by_hash else []
        while queue:
            h = queue.pop(0)
            if h in visited or h not in self._by_hash:
                continue
            visited.add(h)
            entry = self._by_hash[h]
            result.append(entry)
            queue.extend(entry.parent_hashes)
        return result

    def lineage_children(self, expr_hash: str) -> list[FactorCatalogEntry]:
        """All factors that have this factor as a parent."""
        return [e for e in self._entries if expr_hash in e.parent_hashes]

    # --- serialization ---

    def to_json_list(self) -> list[dict[str, Any]]:
        return [asdict(e) for e in self._entries]

    @classmethod
    def from_json_list(
        cls, data: list[dict[str, Any]], max_entries: int = 5000
    ) -> FactorCatalog:
        catalog = cls(max_entries=max_entries)
        for d in data:
            try:
                catalog.record(FactorCatalogEntry(**d))
            except TypeError:
                continue
        return catalog

    # --- internal ---

    def _evict(self) -> None:
        """Evict lowest-value entries to stay within capacity."""
        self._entries.sort(key=lambda e: (e.evaluated, e.fitness))
        while len(self._entries) > self._max_entries:
            removed = self._entries.pop(0)
            self._by_hash.pop(removed.expr_hash, None)


# ---------------------------------------------------------------------------
# Search strategy protocol
# ---------------------------------------------------------------------------


@runtime_checkable
class SearchStrategy(Protocol):
    """Interface that all search strategies must implement.

    To add a new strategy (e.g. from a paper), implement these 4 methods
    and register the strategy with SearchOrchestrator.
    """

    @property
    def name(self) -> str:
        """Strategy name for logging and tracing."""
        ...

    def should_activate(self, ctx: "SearchContext") -> bool:
        """Whether this strategy should run in the current round."""
        ...

    def generate_candidates(self, ctx: "SearchContext") -> list:
        """Generate candidate Individuals (compiled, not yet evaluated)."""
        ...

    def on_evaluation_complete(self, ctx: "SearchContext", evaluated: list) -> None:
        """Callback after evaluation — for internal learning."""
        ...


# ---------------------------------------------------------------------------
# Shared search context
# ---------------------------------------------------------------------------


@dataclass
class SearchContext:
    """Shared state accessible to all strategies via a single object.

    Strategies read/write population and archive through this context,
    enabling indirect collaboration without direct coupling.
    """

    # --- shared collections ---
    population: deque
    archive: dict[tuple[int, int], Any]  # cell -> Individual
    seen_hashes: set[str]
    all_evaluated: list
    details_by_hash: dict[str, dict[str, Any]]

    # --- infrastructure ---
    compiler: Any  # FormulaCompiler
    schema: Any  # TensorSchema
    registry: Any  # OperatorRegistry
    fitness_engine: Any  # FitnessEngine

    # --- evaluation callbacks ---
    evaluate_fn: Callable
    quick_evaluate_fn: Callable | None

    # --- optional enhanced modules ---
    strategy_memory: Any | None  # StrategyMemory
    knowledge_base: Any | None  # FinancialKnowledgeBase
    feature_kitchen: Any | None  # FeatureKitchen

    # --- VM and evaluator (for strategies that need fast screening) ---
    vm: Any | None = None  # StackVM
    evaluator: Any | None = None  # FormulaEvaluator

    # --- dataset (needed by some strategies like MCTS) ---
    dataset: Any | None = None  # AlphaDataset

    # --- search state ---
    round_idx: int = 0
    total_rounds: int = 0
    total_evaluations: int = 0
    total_rejected: int = 0
    batch_size: int = 8

    # --- factor catalog (unified factor tracking) ---
    factor_catalog: FactorCatalog | None = None


# ---------------------------------------------------------------------------
# Individual builder
# ---------------------------------------------------------------------------


def build_individual(
    compiler: Any,
    schema: Any,
    formula: str,
    lineage: Any,
) -> Any | None:
    """Compile a formula into an Individual, or return None on failure.

    Avoids circular imports by deferring the actual construction.
    """
    from .evolution import Individual
    from .pipeline import Lineage

    try:
        program = compiler.compile(formula, schema)
    except (ValueError, SyntaxError):
        return None
    if isinstance(lineage, dict):
        lineage = Lineage.from_dict(lineage)
    return Individual(
        formula=formula,
        program=program,
        expr_hash=program.expr_hash,
        lineage=lineage,
    )
