import logging
from typing import Dict, Optional

from .base import Broker, DataStream, Order, Strategy
from .risk_manager import RiskManager

logger = logging.getLogger(__name__)

class TradingEngine:
    def __init__(self, strategy: Strategy, broker: Broker, data_stream: DataStream,
                 on_step=None, risk_manager: Optional[RiskManager] = None):
        self.strategy = strategy
        self.broker = broker
        self.data_stream = data_stream
        self.on_step = on_step
        self.risk_manager = risk_manager
        self.current_bars = None
        self.last_bars = None

        self.strategy.set_engine(self)
        self.running = False

        logger.info(f"TradingEngine initialized with risk_manager={risk_manager is not None}")

    def submit_order(self, order: Order):
        """Submit order with optional risk check + circuit breaker."""
        # Circuit breaker: check broker consecutive error count
        if hasattr(self.broker, 'consecutive_errors') and self.broker.consecutive_errors >= 5:
            logger.error("熔断器触发: 连续 {} 次下单失败，暂停交易", self.broker.consecutive_errors)
            order.status = "REJECTED"
            order.id = "CIRCUIT_BREAKER"
            return order.id

        # Risk check if risk manager is enabled
        if self.risk_manager and self.risk_manager.enabled:
            current_price = 0.0
            target_bars = self.current_bars or self.last_bars

            if target_bars and order.symbol in target_bars:
                current_price = target_bars[order.symbol].close

            # Check position limit for buy orders
            if order.type == 'buy':
                allowed, reason = self.risk_manager.check_position_limit(
                    order.symbol, order.quantity, current_price
                )
                if not allowed:
                    logger.warning(f"Order rejected by risk manager: {reason}")
                    order.status = "REJECTED"
                    order.id = "RISK_REJECTED"
                    return order.id

        return self.broker.submit_order(order)

    def cancel_order(self, order_id: str):
        return self.broker.cancel_order(order_id)

    def get_risk_status(self) -> Optional[Dict]:
        """Get current risk status"""
        if self.risk_manager:
            return self.risk_manager.get_status()
        return None

    def run(self):
        self.running = True
        logger.info("Trading engine started.")
        last_date = None

        while self.running:
            bars = self.data_stream.next_bar()
            if bars is None:
                logger.info("End of data stream.")
                break

            self.current_bars = bars

            # 0. Reset risk manager at start of new trading day
            current_date = next(iter(bars.values())).timestamp.date()
            if self.risk_manager and last_date and current_date != last_date:
                self.risk_manager.reset_daily()
            last_date = current_date

            # 1. Update broker state and process pending NEXT_OPEN orders
            # These are orders from PREVIOUS bars being filled at CURRENT bar's OPEN
            self.broker.step(bars)

            # 2. Auto-update strategy's current date for logging
            if hasattr(self.strategy, '_update_current_date'):
                self.strategy._update_current_date(bars)

            # 3. Strategy process bars (Signals for NEXT_OPEN or IMMEDIATE_CLOSE)
            self.strategy.on_bar(bars)

            # 4. Process IMMEDIATE orders generated by on_bar
            # Note: IMMEDIATE_OPEN in daily backtest can cause look-ahead bias!
            # Use IMMEDIATE_CLOSE for end-of-bar execution or NEXT_OPEN for next-bar.
            self.broker.process_same_bar_orders(bars, 'IMMEDIATE_OPEN')
            self.broker.process_same_bar_orders(bars, 'IMMEDIATE_CLOSE')

            # 5. Trigger callback for progress tracking
            if self.on_step:
                self.on_step(bars)

            self.last_bars = bars

        # Do NOT run broker.step(last_bars) again here. Orders submitted on the last bar
        # (e.g. JSG rebalance on last trading day of month) are NEXT_OPEN and must fill
        # at the *next* bar's open. If the stream has ended, there is no next bar, so those
        # orders should remain unfilled; filling them at last bar's open would wrongly
        # show execution on the last day (e.g. 2026-01-30) instead of next Monday.

        self.running = False
        logger.info("Trading engine stopped.")

    def stop(self):
        self.running = False
